spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studywords?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: huang1
#    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.qq.com
    username: 904859570@qq.com  # 邮箱地址
    password: xciykfsukpfnbegj # 授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.chun.myspringboot.pojo




